service: Noranoie

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: yarn

provider:
  name: aws
  runtime: nodejs8.10
  stage: develop
  region: ap-northeast-1
  profile: default
  memorySize: 256
  timeout: 5
  deploymentBucket:
    name: noranoie-deploies

plugins:
  - serverless-webpack
  - serverless-offline

package:
  individually: true

functions:
  homepage:
    handler: services/index.handler
    events:
      - http:
          path: /
          method: get
  info:
    handler: services/info.handler
    events:
      - http:
          path: /info/{animalId}
          method: get
          request:
            parameters:
              paths:
                animalId: true
  about:
    handler: functions/about.index
    events:
      - http:
          path: /about
          method: get
