service: Noranoie

provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: ap-northeast-1
  profile: default
  memorySize: 128
  timeout: 5
  deploymentBucket:
    name: noranoie-deploys

plugins:
  - serverless-offline

functions:
  homepage:
    handler: functions/animal.get
    events:
      - http:
          path: /
          method: get
  info:
    handler: functions/info.index
    events:
      - http:
          path: /info/{animalId}
          method: get
          request:
            parameters:
              paths:
                animalId: true
  about:
    handler: functions/about.index
    events:
      - http:
          path: /about
          method: get
  data-gov-tw-query:
    handler: opendata/data-gov-tw.query
    events:
      - http:
          path: /opendata/data.gov.tw
          method: get
