service: Noranoie

provider:
  name: aws
  runtime: nodejs6.10
  stage: develop
  region: ap-northeast-1
  profile: default
  memorySize: 128
  timeout: 5
  deploymentBucket:
    name: noranoie-deploys

functions:
  homepage:
    handler: homepage.index
    events:
      - http:
          path: /
          method: get
  about:
    handler: about.index
    events:
      - http:
          path: /about
          method: get
